# -*- coding: utf-8 -*-
"""week6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqgEzrKUGUmNGDKgKCTBw5Ll-l4Y-Nqb
"""

import matplotlib.pyplot as plt
x=[5,7,6,8,9,10,4,12,14,18,2,16]
y=[55,66,77,33,22,42,24,56,78,90,54,15]
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
from scipy import stats
x=[5,7,6,8,9,10,4,12,14,18,2,16]
y=[55,66,77,33,22,42,24,56,78,90,54,15]
slope,intercept,r,p,std_err=stats.linregress(x,y)
def myfunc(x):
    return slope*x+intercept
mymodel=list(map(myfunc,x))
plt.scatter(x,y)
plt.plot(x,mymodel)
plt.show()

import numpy as np
x=np.arange(1,25).reshape(12,2)
y=np.array([0,1,1,0,1,0,0,1,1,0,1,0])
x

y

pip install sci kit

pip install scikit-learn

from sklearn.model_selection import train_test_split
x_train ,x_test,y_train,y_test=train_test_split(x,y)
x_train

x_test

y_train

y_test

from sklearn.model_selection import train_test_split
x_train ,x_test,y_train,y_test=train_test_split(x,y,test_size=4,random_state=4)
x_train

x_test

y_train

y_test

import numpy as np
x = np.arange(50).reshape(2,25)
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])
print(x)

from sklearn.model_selection import train_test_split
x_train ,x_test,y_train,y_test=train_test_split(x,y,test_size=4,random_state=4,stratify=y)
x_train

x_train

x_train ,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,shuffle=False)
x_train

